#include"SWExpert1_1.h"
#include"SWExpert1_2.h"
#include"chessTeam.h"
#include"GNS.h"
#include"PushOperator.h"
#include<iostream>
#include"CompleteSearch.h"
#include<string.h>
//#include"MinimumPath.h"
#include"MinimumPath2.h"
#include"BinarySubSet.h"
#include"BackJoon.h"
#include"LCP.h"
#include"BC.h"
#include"BoemJoon.h"
#include<iostream>
#include<map>
#include"Processor.h"
#include"JangHoon.h"
#include"ContryTest.h"
#include"MinCut.h"
#include"HongJoon.h"
#include"Counsler.h"
#include"SandTop.h"
#include"Permulation.h"
#include"PushOperator2.h"
#include"Snake.h"
#include"LCS.h"
#include"PoPPing.h"
#include"SeoJoon.h"
#include"Snake2.h"
#include"DIce.h"
#include"Jjaro.h"
#include"2048.h"
using namespace std;

void t()
{
	int id = 100;
	vector<vector<int> > flow = vector<vector<int> >(2 * id + 10, vector<int>(2 * id + 10, 0));
	cout << flow.size();

}

#include"TestSupervisor.h"
#include"Resign.h"
#include"Labaratory.h"
#include"01knapsack.h"
#include"DoubleScale.h"
#include"DonateAngel.h"

#include<stdio.h>
#include<stdlib.h>
#include<time.h>
#include"JaYeong2.h"
#include"StringType.h"
#include"JungTriangle.h"
#include"ManageClub.h"
#include"JongMin.h"
#include"CircularQueue.h"
#include"WaveClass.h"
#include"Dalant.h"
#include"Union.h"
#include"Kaing.h"
#include"BongEoBBangh.h"
#include"N-Queens.h"
#include"DongCheol.h"
#include"MyStack.h"
#include"LineDivide.h"
#include"MyQueue.h"
#include"DBLinkedList.h"
#include"Quicksort.h"
#include"ToOne.h"
#include"BIT.h"
#include"SuJung.h"
#include"SpaceGod.h"
#include"InSuBirthDayParty.h"
#include"InSu_Birthday_Party.h"
#include"YeungJoon_Get_Number.h"
#include"YeongJoon_Scale.h"
#include"Kid_Car_Robot.h"
#include"Nolboo_Salary_Reduction.h"
#include"Maximum_Prize.h"
#include"King's_Position.h"
//#include"YeongJoon_Real_BFS.h"
#include"YeongJoon_Real_BFS_LCA.h"
#include"Make_Password.h"
#include"TermProject.h"
#include"Predicth.h"
#include"HyeonHo_Password.h"
#include"RichProject.h"
#include"City_Maintenance.h"
#include"AllSum.h"
#include"BestTaxiDriver.h"
#include"PerfectShuffle.h"
#include"Hacking.h"
#include"HackingBFS.h"
#include"BreadStroe.h";
#include"PossibleScore.h"
#include"MetalStick.h"
#include"BalabongStory.h"
#include"JongMinHamberger.h"
#include"HyeJungPaint.h"
#include"Ninja_Corp.h"
#include"RamCess.h"
#include"MakeBridge.h"
#include"DesertCafe.h"
#include"homeBangBeom.h"
#include"Balelino.h"
#include"BlockMeSang.h"
#include"FillingMoon.h"
#include"Cooker.h"
#include"Chicken.h"
#include"SecureFilm.h"
#include"DragonCurve.h"
#include"SupervisorCCTV.h"
#include"LiftingLadder.h"
#include"FIndStr.h"
#include"MakeBiggestNumber.h"
int main()
{
	MakeBiggestNumber();

	//Cooker();
	//MakeBridge();
	//HyeJung_Paint();
	//GodHongJoon();
	//HongJoonGod2();
	return 0;
}